In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
from sklearn.model_selection import train_test_split

In [2]:
dataset = pd.read_csv('feature_vec/Image_with_water.txt')
dataset

Unnamed: 0  bit  feature_1  feature_2  feature_3  feature_4
0                0  1.0        0.0       18.5       -5.0        1.5
1                1  1.0       -4.5      -33.5        0.5      -42.0
2                2  1.0       10.5       91.5        5.5       87.0
3                3  1.0      -31.0       -5.5      -35.5       23.5
4                4  1.0      -16.5       13.0      -11.0       -6.0
...            ...  ...        ...        ...        ...        ...
102395      102395  1.0       -6.5        3.0       -1.0        9.0
102396      102396  1.0       -3.5       16.5        0.5       -2.5
102397      102397  1.0        0.5       -8.0        6.5       -2.5
102398      102398  1.0        2.0       28.0       -2.0       49.0
102399      102399  1.0       28.0        3.5       29.5        9.0

[102400 rows x 6 columns]

In [3]:
dataset.dtypes

Unnamed: 0      int64
bit           float64
feature_1     float64
feature_2     float64
feature_3     float64
feature_4     float64
dtype: object

In [4]:
X = dataset.iloc[:,[2,3,4,5]].values
X

array([[  0. ,  18.5,  -5. ,   1.5],
       [ -4.5, -33.5,   0.5, -42. ],
       [ 10.5,  91.5,   5.5,  87. ],
       ...,
       [  0.5,  -8. ,   6.5,  -2.5],
       [  2. ,  28. ,  -2. ,  49. ],
       [ 28. ,   3.5,  29.5,   9. ]])

In [5]:
X.dtype

dtype('float64')

In [6]:
y = dataset.iloc[:, 1].values
y

array([1., 1., 1., ..., 1., 1., 1.])

In [7]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes = (20,15,10,5) , max_iter=1000 ,early_stopping=True , verbose=True)
clf.fit(X, y)


Iteration 1, loss = 0.51546920
Validation score: 0.878516
Iteration 2, loss = 0.26827709
Validation score: 0.927051
Iteration 3, loss = 0.17143271
Validation score: 0.953418
Iteration 4, loss = 0.13213441
Validation score: 0.963867
Iteration 5, loss = 0.11536180
Validation score: 0.973340
Iteration 6, loss = 0.10439656
Validation score: 0.976562
Iteration 7, loss = 0.09641008
Validation score: 0.977832
Iteration 8, loss = 0.09253252
Validation score: 0.976758
Iteration 9, loss = 0.08620055
Validation score: 0.981836
Iteration 10, loss = 0.08437358
Validation score: 0.978906
Iteration 11, loss = 0.07873041
Validation score: 0.982227
Iteration 12, loss = 0.07731325
Validation score: 0.979688
Iteration 13, loss = 0.07280857
Validation score: 0.970605
Iteration 14, loss = 0.07052305
Validation score: 0.982715
Iteration 15, loss = 0.06719965
Validation score: 0.983984
Iteration 16, loss = 0.06866148
Validation score: 0.976660
Iteration 17, loss = 0.06485011
Validation score: 0.985254
Iterat

MLPClassifier(early_stopping=True, hidden_layer_sizes=(20, 15, 10, 5),
              max_iter=1000, verbose=True)

In [8]:
dataset = pd.read_csv('feature_vec/test_data.txt')
dataset

Unnamed: 0  bit  feature_1  feature_2  feature_3  feature_4
0              0  1.0        2.0        0.5        0.0        0.5
1              1  1.0        0.0        0.5        0.0        2.0
2              2  1.0       -0.5        0.5        2.5        0.5
3              3  1.0        1.0       -1.0        0.0        2.5
4              4  1.0        1.5        0.5        0.5        0.5
...          ...  ...        ...        ...        ...        ...
1019        1019  1.0        1.0       -3.0       -3.5       -2.0
1020        1020  1.0       -1.5        3.5        2.0       -1.0
1021        1021  1.0      -10.0       11.0        3.0       -4.0
1022        1022  1.0       -7.5        4.5       -9.0        1.0
1023        1023  1.0       -3.5        3.0       -1.5        0.5

[1024 rows x 6 columns]

In [9]:
X_test = dataset.iloc[:,[2,3,4,5]].values
X_test

array([[  2. ,   0.5,   0. ,   0.5],
       [  0. ,   0.5,   0. ,   2. ],
       [ -0.5,   0.5,   2.5,   0.5],
       ...,
       [-10. ,  11. ,   3. ,  -4. ],
       [ -7.5,   4.5,  -9. ,   1. ],
       [ -3.5,   3. ,  -1.5,   0.5]])

In [10]:
y_test=dataset.iloc[:,1].values
y_test

array([1., 1., 1., ..., 1., 1., 1.])

In [11]:
y_pretict=clf.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pretict)
pd.DataFrame(cm)

0    1
0  292    3
1    6  723

In [13]:
y_pretict=y_pretict.reshape(32,32)
y_pretict

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [14]:
y_pretict[y_pretict>0]=255

In [15]:
y_pretict

array([[255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       ...,
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.]])

In [17]:
from PIL import Image
img = Image.fromarray(y_pretict.astype(np.uint8))
img.show()
          