#### MLP clf

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
from PIL import Image
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report

In [3]:
No_Attack_frame = pd.read_csv('feature_vec/NO_Attack_Random.txt') # ПАРАМЕТР НА ВХОД ФУНКЦИИ
del No_Attack_frame['Unnamed: 0']
X = No_Attack_frame.iloc[:,[1,2,3,4]].values  
Y=No_Attack_frame.iloc[:,[0]].values
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.35, random_state=42)
print(X_test)

[[ 0.  -1.5 -1.   0. ]
 [ 0.   0.  -0.5  0. ]
 [ 1.   1.5 -7.5 -3.5]
 ...
 [-4.5 -4.  -4.  -4. ]
 [-0.5 -0.5 -0.5  0.5]
 [-0.5  0.5 -0.5  0. ]]


In [9]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes = (20,15,10,5) , max_iter=1000 ,early_stopping=True , verbose=True)
clf.fit(X_train, y_train)

d:\code\python\nir\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 0.66450674
Validation score: 0.711388
Iteration 2, loss = 0.51654253
Validation score: 0.846605
Iteration 3, loss = 0.35755427
Validation score: 0.902644
Iteration 4, loss = 0.27441367
Validation score: 0.919922
Iteration 5, loss = 0.22798112
Validation score: 0.934044
Iteration 6, loss = 0.20252466
Validation score: 0.942909
Iteration 7, loss = 0.18199859
Validation score: 0.945012
Iteration 8, loss = 0.16660965
Validation score: 0.950270
Iteration 9, loss = 0.15676926
Validation score: 0.958233
Iteration 10, loss = 0.14370857
Validation score: 0.964994
Iteration 11, loss = 0.13531898
Validation score: 0.959435
Iteration 12, loss = 0.12954419
Validation score: 0.967698
Iteration 13, loss = 0.12365530
Validation score: 0.969802
Iteration 14, loss = 0.11880848
Validation score: 0.965595
Iteration 15, loss = 0.11684146
Validation score: 0.968900
Iteration 16, loss = 0.11455130
Validation score: 0.973558
Iteration 17, loss = 0.11015127
Validation score: 0.969802
Iterat

MLPClassifier(early_stopping=True, hidden_layer_sizes=(20, 15, 10, 5),
              max_iter=1000, verbose=True)

In [10]:
y_predict=clf.predict(X_test)
from sklearn.metrics import confusion_matrix
print(classification_report(y_test, y_predict))
cm = confusion_matrix(y_test, y_predict)
pd.DataFrame(cm)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98     18625
           1       0.98      0.98      0.98     17215

    accuracy                           0.98     35840
   macro avg       0.98      0.98      0.98     35840
weighted avg       0.98      0.98      0.98     35840



0      1
0  18288    337
1    312  16903

In [30]:
No_Attack_frame = pd.read_csv('feature_vec/NO_Attack_Dota.txt') # ПАРАМЕТР НА ВХОД ФУНКЦИИ
del No_Attack_frame['Unnamed: 0']
X = No_Attack_frame.iloc[:,[1,2,3,4]].values  
Y=No_Attack_frame.iloc[:,[0]].values
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.35, random_state=42)
print(X_test)

[[ 0.  -1.5 -1.   0. ]
 [ 0.   0.  -0.5  0. ]
 [ 1.   1.5 -7.5 -3.5]
 ...
 [-4.5 -4.  -4.  -4. ]
 [-0.5 -0.5 -0.5  0.5]
 [-0.5  0.5 -0.5  0. ]]


In [31]:
y_predict=clf.predict(X_test)
from sklearn.metrics import confusion_matrix
print(classification_report(y_test, y_predict))
cm = confusion_matrix(y_test, y_predict)
pd.DataFrame(cm)

              precision    recall  f1-score   support

           0       0.99      0.98      0.99     26290
           1       0.95      0.98      0.97      9550

    accuracy                           0.98     35840
   macro avg       0.97      0.98      0.98     35840
weighted avg       0.98      0.98      0.98     35840



0     1
0  25807   483
1    160  9390

In [28]:
No_Attack_frame = pd.read_csv('feature_vec/NO_Attack_CROSS.txt') # ПАРАМЕТР НА ВХОД ФУНКЦИИ
del No_Attack_frame['Unnamed: 0']
X_image_test = No_Attack_frame.iloc[:,[1,2,3,4]].values  
y_image_test = No_Attack_frame.iloc[:,[0]].values  

i=5
y_test=y_image_test[1024*i:1024*(i+1)]
y=X_image_test[1024*i:1024*(i+1)]
y_predict_image=clf.predict(y)
cm = confusion_matrix(y_predict_image, y_test)
print(pd.DataFrame(cm))
y_predict_image[y_predict_image>0]=255
y_predict_image=y_predict_image.reshape(32,32)
img = Image.fromarray(y_predict_image.astype(np.uint8))
img.show()


     0    1
0  288   10
1    8  718


In [34]:
No_Attack_frame = pd.read_csv('feature_vec/NO_Attack_Dota.txt') # ПАРАМЕТР НА ВХОД ФУНКЦИИ
del No_Attack_frame['Unnamed: 0']
X_image_test = No_Attack_frame.iloc[:,[1,2,3,4]].values  
y_image_test = No_Attack_frame.iloc[:,[0]].values  

i=3
y_test=y_image_test[1024*i:1024*(i+1)]
y=X_image_test[1024*i:1024*(i+1)]
y_predict_image=clf.predict(y)
cm = confusion_matrix(y_predict_image, y_test)
print(pd.DataFrame(cm))
y_predict_image[y_predict_image>0]=255
y_predict_image=y_predict_image.reshape(32,32)
img = Image.fromarray(y_predict_image.astype(np.uint8))
img.show()

     0    1
0  741    6
1   11  266


In [32]:
No_Attack_frame = pd.read_csv('feature_vec/NO_Attack_CROSS.txt') # ПАРАМЕТР НА ВХОД ФУНКЦИИ
del No_Attack_frame['Unnamed: 0']
X = No_Attack_frame.iloc[:,[1,2,3,4]].values  
Y=No_Attack_frame.iloc[:,[0]].values
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.35, random_state=42)
print(X_test)

[[ 0.  -1.5 -1.   3. ]
 [ 0.   0.   1.5  0. ]
 [ 1.   3.5 -7.5 -3.5]
 ...
 [-4.5  1.  -4.  -4. ]
 [-0.5 -0.5 -0.5  0.5]
 [-0.5  0.5 -0.5  2. ]]


In [33]:
y_predict=clf.predict(X_test)
from sklearn.metrics import confusion_matrix
print(classification_report(y_test, y_predict))
cm = confusion_matrix(y_test, y_predict)
pd.DataFrame(cm)

              precision    recall  f1-score   support

           0       0.96      0.98      0.97     10443
           1       0.99      0.98      0.99     25397

    accuracy                           0.98     35840
   macro avg       0.98      0.98      0.98     35840
weighted avg       0.98      0.98      0.98     35840



0      1
0  10251    192
1    415  24982