In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
from PIL import Image
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report

In [27]:
AttackDataFrame = pd.read_csv('feature_vec/RandomWMFeatVec.txt')
del AttackDataFrame['Unnamed: 0']
AttackDataFrame

bit  feature_1  feature_2  feature_3  feature_4
0       1       -4.5       -1.0       -3.5       -2.0
1       0       -3.5        1.5       -8.5        1.0
2       1        3.5       -1.0        1.5        0.0
3       1       16.0        6.0       18.5        2.0
4       1       -0.5       -2.0        1.0       -3.0
...   ...        ...        ...        ...        ...
1019    0      251.0      -12.0      251.0       -4.5
1020    1       -7.5       71.0      -22.0       69.5
1021    1        1.0        0.0        0.0        0.0
1022    1        1.0       -1.0        0.0       -1.0
1023    0       -0.5       -2.0       -1.0        0.0

[1024 rows x 5 columns]

In [37]:
X = AttackDataFrame.iloc[:,[1,2,3,4]].values  
X

array([[-4.5, -1. , -3.5, -2. ],
       [-3.5,  1.5, -8.5,  1. ],
       [ 3.5, -1. ,  1.5,  0. ],
       ...,
       [ 1. ,  0. ,  0. ,  0. ],
       [ 1. , -1. ,  0. , -1. ],
       [-0.5, -2. , -1. ,  0. ]])

In [38]:
Y=AttackDataFrame.iloc[:,[0]].values
Y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]], dtype=int64)

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.9, random_state=42)


In [40]:
X_train.size

408

In [41]:
X_test

array([[ -8. ,  11. , -14. ,  19. ],
       [  8.5,  10. ,  -1.5,  17.5],
       [ -3. , -92. ,  -3.5, -33.5],
       ...,
       [ -1. ,   0. ,  -0.5,  -1. ],
       [ -1. ,  -1. ,  -1. ,  -1. ],
       [ -2. ,   7.5,  -9. ,   4.5]])

In [42]:
y_train.size 

102

In [43]:
y_test.size

922

In [44]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes = (20,15,10,5) , max_iter=1000 ,early_stopping=True , verbose=True)
clf.fit(X_train, y_train)

Iteration 1, loss = 1.27059107
Validation score: 0.454545
Iteration 2, loss = 1.21297723
Validation score: 0.454545
Iteration 3, loss = 1.16237101
Validation score: 0.454545
Iteration 4, loss = 1.12619952
Validation score: 0.454545
Iteration 5, loss = 1.09311377
Validation score: 0.454545
Iteration 6, loss = 1.06092773
Validation score: 0.545455
Iteration 7, loss = 1.03006874
Validation score: 0.545455
Iteration 8, loss = 1.00135013
Validation score: 0.545455
Iteration 9, loss = 0.97417017
Validation score: 0.545455
Iteration 10, loss = 0.94755998
Validation score: 0.545455
Iteration 11, loss = 0.92067697
Validation score: 0.545455
Iteration 12, loss = 0.89522708
Validation score: 0.545455
Iteration 13, loss = 0.87110367
Validation score: 0.545455
Iteration 14, loss = 0.84868847
Validation score: 0.545455
Iteration 15, loss = 0.82667657
Validation score: 0.545455
Iteration 16, loss = 0.80519526
Validation score: 0.545455
Iteration 17, loss = 0.78360407
Validation score: 0.545455
Valida

d:\code\python\nir\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(early_stopping=True, hidden_layer_sizes=(20, 15, 10, 5),
              max_iter=1000, verbose=True)

In [45]:
y_predict=clf.predict(X_test)
y_predict.size

922

In [46]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predict)
pd.DataFrame(cm)

0    1
0  132  333
1  129  328

In [47]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.51      0.28      0.36       465
           1       0.50      0.72      0.59       457

    accuracy                           0.50       922
   macro avg       0.50      0.50      0.48       922
weighted avg       0.50      0.50      0.47       922



In [49]:
X_image_test = AttackDataFrame.iloc[:,[1,2,3,4]].values  
i=0
y=X_image_test[1024*i:1024*(i+1)]
y_predict_image=clf.predict(y)
y_predict_image[y_predict_image>0]=255
y_predict_image=y_predict_image.reshape(32,32)
img = Image.fromarray(y_predict_image.astype(np.uint8))
img.show()

In [21]:
imageWM2Frame = pd.read_csv('feature_vec/Task1/anotherCWFearVec.txt')
del imageWM2Frame['Unnamed: 0']
imageWM2Frame

bit  feature_1  feature_2  feature_3  feature_4
0       1        6.5        5.5        8.5        7.5
1       1       10.5       -8.5       -1.5       -1.5
2       1       -1.0      -15.5      -12.5        9.5
3       1      -18.5       25.0       12.5       -5.5
4       1        6.5      -26.0        0.0        4.0
...   ...        ...        ...        ...        ...
1019    1       14.0       25.5        6.0        7.0
1020    1      -19.5       34.5      -22.0      -44.0
1021    1       -0.5        9.0       28.5       33.0
1022    1      -49.5      -33.0      -11.0      -29.5
1023    1       -1.5        2.0      -14.0      -28.0

[1024 rows x 5 columns]

In [22]:
XimageWM2 = imageWM2Frame.iloc[:,[1,2,3,4]].values  
XimageWM2.size

4096

In [23]:
YimageWM2=imageWM2Frame.iloc[:,[0]].values
YimageWM2

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [28]:
y_predict_cw2=clf.predict(XimageWM2)
y_predict_cw2.size



1024

In [29]:
cm = confusion_matrix(YimageWM2, y_predict_cw2)
pd.DataFrame(cm)

0    1
0  442   14
1    8  560

In [30]:
print(classification_report(YimageWM2, y_predict_cw2))

              precision    recall  f1-score   support

           0       0.98      0.97      0.98       456
           1       0.98      0.99      0.98       568

    accuracy                           0.98      1024
   macro avg       0.98      0.98      0.98      1024
weighted avg       0.98      0.98      0.98      1024



In [31]:
y_predict_cw2[y_predict_cw2>0]=255
y_predict_cw2=y_predict_cw2.reshape(32,32)
img = Image.fromarray(y_predict_cw2.astype(np.uint8))
img.show()