In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
from PIL import Image
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report

In [4]:
AttackDataFrame = pd.read_csv('feature_vec/Task1/Task1FeatureVec.txt')
del AttackDataFrame['Unnamed: 0']
AttackDataFrame

bit  feature_1  feature_2  feature_3  feature_4
0         1        0.0       18.5       -5.0        1.5
1         1       -4.5      -33.5        0.5      -42.0
2         1       10.5       91.5        5.5       87.0
3         1      -31.0       -5.5      -35.5       23.5
4         1      -16.5       13.0      -11.0       -6.0
...     ...        ...        ...        ...        ...
204795    1       -6.5        3.0       -1.0        9.0
204796    1       -3.5       16.5        0.5       -2.5
204797    1        0.5       -8.0        6.5       -2.5
204798    1        2.0       28.0       -2.0       49.0
204799    1       28.0        3.5       29.5        9.0

[204800 rows x 5 columns]

In [5]:
X = AttackDataFrame.iloc[:,[1,2,3,4]].values  
X

array([[  0. ,  18.5,  -5. ,   1.5],
       [ -4.5, -33.5,   0.5, -42. ],
       [ 10.5,  91.5,   5.5,  87. ],
       ...,
       [  0.5,  -8. ,   6.5,  -2.5],
       [  2. ,  28. ,  -2. ,  49. ],
       [ 28. ,   3.5,  29.5,   9. ]])

In [6]:
Y=AttackDataFrame.iloc[:,[0]].values
Y

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.7, random_state=42)


In [8]:
X_train.size

245760

In [9]:
X_test

array([[ 0.5, -3. ,  4.5, -0.5],
       [ 1.5,  0.5, -2. ,  0.5],
       [-0.5,  0. , -0.5, -0.5],
       ...,
       [ 2. , -0.5, -1. , -0.5],
       [-0.5, -1.5, -0.5,  1. ],
       [-2.5, -4. , -2.5, -4. ]])

In [10]:
y_train.size 

61440

In [11]:
y_test.size

143360

In [12]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes = (20,15,10,5) , max_iter=1000 ,early_stopping=True , verbose=True)
clf.fit(X_train, y_train)

d:\code\python\nir\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 0.70662796
Validation score: 0.716471
Iteration 2, loss = 0.54382141
Validation score: 0.795410
Iteration 3, loss = 0.37273331
Validation score: 0.908366
Iteration 4, loss = 0.25719390
Validation score: 0.929362
Iteration 5, loss = 0.18681118
Validation score: 0.953613
Iteration 6, loss = 0.15086675
Validation score: 0.962240
Iteration 7, loss = 0.13243399
Validation score: 0.967448
Iteration 8, loss = 0.11802970
Validation score: 0.966471
Iteration 9, loss = 0.11325402
Validation score: 0.972656
Iteration 10, loss = 0.09851262
Validation score: 0.975911
Iteration 11, loss = 0.09419088
Validation score: 0.975586
Iteration 12, loss = 0.08873335
Validation score: 0.978353
Iteration 13, loss = 0.08408035
Validation score: 0.978841
Iteration 14, loss = 0.08040519
Validation score: 0.978353
Iteration 15, loss = 0.07752972
Validation score: 0.980306
Iteration 16, loss = 0.07560731
Validation score: 0.980469
Iteration 17, loss = 0.07441772
Validation score: 0.981283
Iterat

MLPClassifier(early_stopping=True, hidden_layer_sizes=(20, 15, 10, 5),
              max_iter=1000, verbose=True)

In [13]:
y_predict=clf.predict(X_test)
y_predict.size

143360

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predict)
pd.DataFrame(cm)

0      1
0  59174    642
1    989  82555

In [15]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99     59816
           1       0.99      0.99      0.99     83544

    accuracy                           0.99    143360
   macro avg       0.99      0.99      0.99    143360
weighted avg       0.99      0.99      0.99    143360



In [16]:
X_image_test = AttackDataFrame.iloc[:,[1,2,3,4]].values  
i=1
y=X_image_test[1024*i:1024*(i+1)]
y_predict_image=clf.predict(y)
y_predict_image[y_predict_image>0]=255
y_predict_image=y_predict_image.reshape(32,32)
img = Image.fromarray(y_predict_image.astype(np.uint8))
img.show()

In [31]:
imageWM2Frame = pd.read_csv('feature_vec/anotherCWFearVec.txt')
del imageWM2Frame['Unnamed: 0']
imageWM2Frame

bit  feature_1  feature_2  feature_3  feature_4
0       0       -2.5        3.5       -1.0        3.0
1       0        3.0        1.0        3.0        3.0
2       1        0.5        0.5       -1.5        2.5
3       1        0.0        0.5       -0.5        2.5
4       1       -0.5       35.5       -1.5       38.5
...   ...        ...        ...        ...        ...
1019    0        0.0       -1.5       -2.0        0.0
1020    0        0.0      -11.0        1.0        1.0
1021    0        3.5        3.5        3.5      -27.5
1022    0       11.0      -11.5      -14.0       10.5
1023    0        0.5        0.0      -12.5       -3.5

[1024 rows x 5 columns]

In [33]:
XimageWM2 = imageWM2Frame.iloc[:,[1,2,3,4]].values  
XimageWM2.size

4096

In [34]:
YimageWM2=imageWM2Frame.iloc[:,[0]].values
YimageWM2

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [39]:
y_predict_cw2=clf.predict(XimageWM2)
y_predict_cw2.size



1024

In [40]:
cm = confusion_matrix(YimageWM2, y_predict_cw2)
pd.DataFrame(cm)

0    1
0  348    3
1   14  659

In [42]:
y_predict_cw2[y_predict_cw2>0]=255
y_predict_cw2=y_predict_cw2.reshape(32,32)
img = Image.fromarray(y_predict_cw2.astype(np.uint8))
img.show()