In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
from PIL import Image
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report

In [2]:
AttackDataFrame = pd.read_csv('feature_vec/Task1FeatureVec.txt')
del AttackDataFrame['Unnamed: 0']
AttackDataFrame

bit  feature_1  feature_2  feature_3  feature_4
0         1        0.0       18.5       -5.0        1.5
1         1       -4.5      -33.5        0.5      -42.0
2         1       10.5       91.5        5.5       87.0
3         1      -31.0       -5.5      -35.5       23.5
4         1      -16.5       13.0      -11.0       -6.0
...     ...        ...        ...        ...        ...
204795    1       -6.5        3.0       -1.0        9.0
204796    1       -3.5       16.5        0.5       -2.5
204797    1        0.5       -8.0        6.5       -2.5
204798    1        2.0       28.0       -2.0       49.0
204799    1       28.0        3.5       29.5        9.0

[204800 rows x 5 columns]

In [3]:
X = AttackDataFrame.iloc[:,[1,2,3,4]].values  
X

array([[  0. ,  18.5,  -5. ,   1.5],
       [ -4.5, -33.5,   0.5, -42. ],
       [ 10.5,  91.5,   5.5,  87. ],
       ...,
       [  0.5,  -8. ,   6.5,  -2.5],
       [  2. ,  28. ,  -2. ,  49. ],
       [ 28. ,   3.5,  29.5,   9. ]])

In [4]:
Y=AttackDataFrame.iloc[:,[0]].values
Y

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.7, random_state=42)


In [14]:
X_train.size

245760

In [19]:
X_test

array([[ 0.5, -3. ,  4.5, -0.5],
       [ 1.5,  0.5, -2. ,  0.5],
       [-0.5,  0. , -0.5, -0.5],
       ...,
       [ 2. , -0.5, -1. , -0.5],
       [-0.5, -1.5, -0.5,  1. ],
       [-2.5, -4. , -2.5, -4. ]])

In [17]:
y_train.size 

61440

In [18]:
y_test.size

143360

In [10]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes = (20,15,10,5) , max_iter=1000 ,early_stopping=True , verbose=True)
clf.fit(X_train, y_train)

d:\code\python\nir\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 0.65099337
Validation score: 0.706543
Iteration 2, loss = 0.51493622
Validation score: 0.828288
Iteration 3, loss = 0.36363961
Validation score: 0.913574
Iteration 4, loss = 0.25318684
Validation score: 0.946777
Iteration 5, loss = 0.20118360
Validation score: 0.957520
Iteration 6, loss = 0.17154185
Validation score: 0.963379
Iteration 7, loss = 0.15875668
Validation score: 0.960612
Iteration 8, loss = 0.14658581
Validation score: 0.969564
Iteration 9, loss = 0.13715310
Validation score: 0.962565
Iteration 10, loss = 0.13143832
Validation score: 0.973470
Iteration 11, loss = 0.12523454
Validation score: 0.973145
Iteration 12, loss = 0.11857813
Validation score: 0.974121
Iteration 13, loss = 0.11180569
Validation score: 0.971680
Iteration 14, loss = 0.10778264
Validation score: 0.978841
Iteration 15, loss = 0.10303657
Validation score: 0.978678
Iteration 16, loss = 0.10039036
Validation score: 0.976725
Iteration 17, loss = 0.09843656
Validation score: 0.976562
Iterat

MLPClassifier(early_stopping=True, hidden_layer_sizes=(20, 15, 10, 5),
              max_iter=1000, verbose=True)

In [11]:
y_predict=clf.predict(X_test)
y_predict.size

143360

In [12]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predict)
pd.DataFrame(cm)

0      1
0  58926    890
1   1330  82214

In [13]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98     59816
           1       0.99      0.98      0.99     83544

    accuracy                           0.98    143360
   macro avg       0.98      0.98      0.98    143360
weighted avg       0.98      0.98      0.98    143360



In [25]:
X_image_test = AttackDataFrame.iloc[:,[1,2,3,4]].values  
i=1
y=X_image_test[1024*i:1024*(i+1)]
y_predict_image=clf.predict(y)
y_predict_image[y_predict_image>0]=255
y_predict_image=y_predict_image.reshape(32,32)
img = Image.fromarray(y_predict_image.astype(np.uint8))
img.show()